// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juyyeihmszkdiltwcnpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eXllaWhtc3prZGlsdHdjbnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTI4NjUsImV4cCI6MjA2NDAyODg2NX0.ohsOSXd2FSxp4T08Mtp_cl4C5Sglwz81vEoP94Wnw2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);